name: CLI Tests
on: [push, pull_request]
jobs:
  cli_tests:
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.12.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download Dependencies
        run: go get -v -t -d ./cli/...

      - name: Test
        run: go test -v ./cli/...
